# Generated by Django 6.0.1 on 2026-03-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_url_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
